# Generated by Django 2.2.3 on 2019-07-10 14:30

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='blog_summary',
            field=wagtail.core.fields.RichTextField(help_text='Provide a short summary of what this blog post is about.', null=True),
        ),
    ]
