# Generated by Django 2.2.3 on 2019-07-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0002_blogdetailpage_blog_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloglistingpage',
            options={'verbose_name': 'Blog Listing', 'verbose_name_plural': 'Blog Listings'},
        ),
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Author's first name", max_length=100, null=True)),
                ('last_name', models.CharField(help_text="Author's last name", max_length=120, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': ('Blog Author',),
                'verbose_name_plural': 'Blog Authors',
            },
        ),
    ]
