# Generated by Django 2.2.3 on 2019-07-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0006_auto_20190714_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlogPage',
            fields=[
                ('blogdetailpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogDetailPage')),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('intro_image', models.ForeignKey(blank=True, help_text='Best size for this image will be 1200x300', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogdetailpage',),
        ),
    ]
