# Generated by Django 2.2.3 on 2019-07-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_videoblogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoblogpage',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
