# Generated by Django 2.2.3 on 2019-07-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190720_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoblogpage',
            name='youtube_video_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
