# Generated by Django 2.2.3 on 2019-07-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagecarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarousel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecarousel',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
