# Generated by Django 2.2.3 on 2019-07-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190706_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarousel',
            name='text_orient',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], max_length=20, null=True),
        ),
    ]
